name: ConfigManager
version: '1'
main: com.czrbyn.configManager.ConfigManager
api-version: '1.21'
commands:
  configmanager:
    aliases:
      - cfgmanager
      - cfg
    description: Main command for the ConfigManager plugin
